python3 train.py -root dataset_han_nom_real_synth \
                 -exp /content/drive/MyDrive/Master/NLP \
                 -nep 60000 \
                 -lr 1e-3 \
                 -its 100 \
                 -cTr 100 \
                 -nsTr 5 \
                 -nqTr 5 \
                 -cVa 100 \
                 -nsVa 2 \
                 -nqVa 1 \
                 -seed 2103 \
                 --cuda